### ISSUE TITLE
selection of sampleSize

### ISSUE THREAD

**Issue by jfertaj** [yueli-compbio/RiVIERA#7]
Hi @yueli-compbio ,

Thanks for developing this interesting tool, I have a few questions:

1) Can I use ld matrix generated in PAINTOR
2) the sampleSize parameter and max_iter parameter have default values or do you need to change them according to your experiment?

I am trying to make finemapping of one locus with 200 snps in that locus

**Comment by yueli-compbio** [comment]
Thank you for your interest. 
1. Yes LD matrix (i.e., Pearson correlation) is the same for both RiVIERA and PAINTOR.
2. Depending on the configSampleScheme: 1: neighborhood search (slow but accurate if the LD matrix is accurate); 2: importance sampling (fast but not as accurate as 1 especially if the LD matrix is not accurate). If you use configSampleScheme 1, set sampleSize to 10 (i.e., 10 recursive stochastic samplings from all neighborhoods at each sampled configuration); if you use configSampleScheme 2, set sampleSize to 100-1000 (i.e., sample 100-1000 configurations from the proposed distribution).

If your locus only has 200 SNPs and you know the LD is accurate, i would recommend use the first sampling option.

**Comment by jfertaj** [comment]
thanks a lot @yueli-compbio, I have run RiVIERA following your suggestions but i get this error

`Error in riviera_fmap(zscore = tanc1.zscore, ldmat = ldmatlist, ann = tanc1.ann,  : 
  lld_causal/lld_null is not finite!`

Any ideas?

**Comment by yueli-compbio** [comment]
Among other possible reasons, it’s likely due to the inversion of the LD matrix.

**Comment by jfertaj** [comment]
And how I correct this issue?

**Comment by yueli-compbio** [comment]
Try using an invertible LD matrix. Or if you can wait, please send me the 200-SNP data and LD matrix you use to run it, and i will look into it.

**Comment by jfertaj** [comment]
Here is the file I have used and the LD matrix, and thanks for look at it
[Archive.zip](https://github.com/yueli-compbio/RiVIERA/files/1563146/Archive.zip)

**Comment by yueli-compbio** [comment]
No annotation?

**Comment by jfertaj** [comment]
ups I forgot to include it, attached now!! Thanks a lot!!!
[TANC1.annotations.zip](https://github.com/yueli-compbio/RiVIERA/files/1563346/TANC1.annotations.zip)
