### ISSUE TITLE
non-invertible LD matrix

### ISSUE THREAD

**Issue by jfertaj** [yueli-compbio/RiVIERA#8]
Hi @yueli-compbio, 

Sorry for bothering you in this dates but I am trying to make RiVIERA works, and it is giving me a really hard time, I have tried to run it but always get `Error in riviera_fmap(zscore = tanc1.zscore, ldmat = ldmatlist, ann = tanc1.ann2,  : 
  lld_causal/lld_null is not finite!` 

You point me to a problem with the LD matrix, I generated a new one using LDlink but when I try to invert them as you suggested it is not invertible, could it be the problem? and if so, could you help me to solve it?

Thanks a lot

**Comment by yueli-compbio** [comment]
Hi,

Sorry for the delay. Here is the Rmd file for running your data, which include transforming LD.

**Comment by jfertaj** [comment]
thanks a lot @yueli-compbio, but I can't see any atachment...

**Comment by yueli-compbio** [comment]
[jfertaj.zip](https://github.com/yueli-compbio/RiVIERA/files/1585048/jfertaj.zip)

**Comment by jfertaj** [comment]
Hi @yueli-compbio, thanks a lot for the code, it works like a charm. Do you have any recommendations in how many times do I need to run the code? Every time I ran the code I get different posteriors and also a different number of SNPs with pip > 0. Although the SNP with the highest prior is always the same

**Comment by yueli-compbio** [comment]
Because it's stochastic sampling, you will get different numerical values each time. But typically, the relative levels of posteriors are the same with enough samplings.
